# NOTE:
# This builder configuration is NOT used to build any official binary.
# To see the builder manifests used for official binaries,
# check https://github.com/open-telemetry/opentelemetry-collector-releases
#
# For the OpenTelemetry Collector Contrib official distribution sources, check
# https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib

dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol
  name: otelcontribcol
  description: Local OpenTelemetry Collector Contrib binary, testing only.
  version: 0.115.0-dev
  output_path: /build/otelcol-dev

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.115.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.115.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.115.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.115.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.115.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.115.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.115.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.115.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.115.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.115.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.115.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.115.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.21.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.21.0

replaces:
#   - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter => ../../exporter/clickhouseexporter
  - github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter => /opentelemetry-collector-contrib/exporter/kafkaexporter
#   - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver => ../../receiver/kafkareceiver
#   - github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite => ../../pkg/translator/prometheusremotewrite
